// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAToOGwdUMuVcP-_eLoSITqGyNzFoqQXCU',
    appId: '1:1012897909513:web:367fded651c703bbe9e1d8',
    messagingSenderId: '1012897909513',
    projectId: 'ecommerce-d93f8',
    authDomain: 'ecommerce-d93f8.firebaseapp.com',
    storageBucket: 'ecommerce-d93f8.firebasestorage.app',
    measurementId: 'G-W085TF4N9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVhHr6F6IuCu-yslp6k9Jhm0Or6qpnj4',
    appId: '1:1012897909513:android:287415c27d87be93e9e1d8',
    messagingSenderId: '1012897909513',
    projectId: 'ecommerce-d93f8',
    storageBucket: 'ecommerce-d93f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3HEGwhVX2j6lQn-7ACf9L8QoIMUPKup0',
    appId: '1:1012897909513:ios:a6f2fe3ceffdb651e9e1d8',
    messagingSenderId: '1012897909513',
    projectId: 'ecommerce-d93f8',
    storageBucket: 'ecommerce-d93f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3HEGwhVX2j6lQn-7ACf9L8QoIMUPKup0',
    appId: '1:1012897909513:ios:a6f2fe3ceffdb651e9e1d8',
    messagingSenderId: '1012897909513',
    projectId: 'ecommerce-d93f8',
    storageBucket: 'ecommerce-d93f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAToOGwdUMuVcP-_eLoSITqGyNzFoqQXCU',
    appId: '1:1012897909513:web:257864f16939c156e9e1d8',
    messagingSenderId: '1012897909513',
    projectId: 'ecommerce-d93f8',
    authDomain: 'ecommerce-d93f8.firebaseapp.com',
    storageBucket: 'ecommerce-d93f8.firebasestorage.app',
    measurementId: 'G-09WJKTDB83',
  );
}
